docs: updates `brew` command to use new cask syntax
`brew cask` is deprecated and no longer works.

```
$> brew cask install session-manager-plugin
Error: Unknown command: cask
```